// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2o92r4HouWuiLaDt-sckM5mx2NrivVzQ',
    appId: '1:128010174723:web:d805f112f4bd874b272936',
    messagingSenderId: '128010174723',
    projectId: 'coffe-well-doco',
    authDomain: 'coffe-well-doco.firebaseapp.com',
    storageBucket: 'coffe-well-doco.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6K4fFMhPed8aTG56nh7VNinDpXTehBSM',
    appId: '1:128010174723:android:b7bd7fa062cedb18272936',
    messagingSenderId: '128010174723',
    projectId: 'coffe-well-doco',
    storageBucket: 'coffe-well-doco.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJdiyx-KLg1dLeSzpIuYqRbqncofCn2-s',
    appId: '1:128010174723:ios:06a515aa584fcb6b272936',
    messagingSenderId: '128010174723',
    projectId: 'coffe-well-doco',
    storageBucket: 'coffe-well-doco.firebasestorage.app',
    iosBundleId: 'com.example.cafeWellDoco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJdiyx-KLg1dLeSzpIuYqRbqncofCn2-s',
    appId: '1:128010174723:ios:06a515aa584fcb6b272936',
    messagingSenderId: '128010174723',
    projectId: 'coffe-well-doco',
    storageBucket: 'coffe-well-doco.firebasestorage.app',
    iosBundleId: 'com.example.cafeWellDoco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2o92r4HouWuiLaDt-sckM5mx2NrivVzQ',
    appId: '1:128010174723:web:a9894fddfacebdd7272936',
    messagingSenderId: '128010174723',
    projectId: 'coffe-well-doco',
    authDomain: 'coffe-well-doco.firebaseapp.com',
    storageBucket: 'coffe-well-doco.firebasestorage.app',
  );

}